version: '3.5'

services:
  kibana:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      SERVER_NAME: kibana.${PUBLIC_HOSTNAME}
      ELASTICSEARCH_URL: http://${ELASTICSEARCH_URL}:${ELASTICSEARCH_PORT}
      ELASTICSEARCH_PASSWORD: "${ELASTIC_USER_PASS}"
    networks:
      - elastic-net
      - traefik-net

networks:
  elastic-net:
    external: true

  traefik-net:
    external: true
