version: '3.5'

services:
  kibana:
    ports:
      - target: ${PORT}
        published: ${PORT}
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.port: "${PORT}"
        traefik.docker.network: traefik-net
        traefik.frontend.rule: Host:kibana.${PUBLIC_HOSTNAME}
        traefik.backend: kibana
      restart_policy:
        delay: 1m
        window: 2m
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          memory: 820M
