version: '3.5'

services:
  kibana:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - SERVER_NAME=kibana.${PUBLIC_HOSTNAME}
      - XPACK_SECURITY_ENABLED=false
      - XPACK_SPACES_ENABLED=false
      - XPACK_CANVAS_ENABLED=false
      - XPACK_MONITORING_ENABLED=false
      - XPACK_GRAPH_ENABLED=false
      - XPACK_ML_ENABLED=false
      - XPACK_WATCHER_ENABLED=false
      - XPACK_APM_ENABLED=false
      - XPACK_INFRA_ENABLED=false
      - XPACK_LOGSTASH_ENABLED=false
      - ELASTICSEARCH_URL
      - ELASTICSEARCH_USERNAME
      - ELASTICSEARCH_PASSWORD
    networks:
      - elastic-net
      - traefik-net
    configs:
      - source: logtrail-json
        target: /usr/share/kibana/plugins/logtrail/logtrail.json
    healthcheck:
      test: curl --silent http://localhost:${PORT}
      interval: 30s
      timeout: 1m
      retries: 3
      start_period: 2m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.frontend.rule: Host:kibana.${PUBLIC_HOSTNAME}
        traefik.backend: kibana
        traefik.port: "${PORT}"
      restart_policy:
        delay: 10s
        window: 2m
      resources:
        limits:
          cpus: '2'
          memory: 3G
        reservations:
          memory: 512M

networks:
  elastic-net:
    name: ${ELASTIC_NET_NAME:-elastic6-net}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

configs:
  logtrail-json:
    name: ${LOGTRAIL_JSON_NAME:-logtrail-json}
    file: ./config/logtrail.json
